[package]
name = "wasm-demo-rs"
version = "0.1.0"
authors = ["Lucas Vieira <lucasvieira@protonmail.com>"]
description = "A basic example of Rust being compiled to WebAssembly, using Rust's own native tools. Requires nightly toolchain."

[dependencies]


[dependencies.stdweb]
version = "0.3"
